project:
  type: website

website:
  title: "Sandpiles blog"
  page-footer:
    left: "Blog made with [Quarto](https://quarto.org/), by Jordi M. Blanch. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/sandpiles/
      - icon: twitter
        href: https://twitter.com/jmblanch
      - icon: envelope
        href: mailto:blanch2008@gmail.com
  twitter-card:
    creator: "@jmblanch"
    card-style: summary_large_image
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

